# Generated by Django 6.0.2 on 2026-02-07 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('message', models.TextField(verbose_name='message')),
                ('notif_type', models.CharField(choices=[('info', 'Information'), ('success', 'Succes'), ('warning', 'Avertissement'), ('error', 'Erreur')], default='info', max_length=20, verbose_name='type')),
                ('is_read', models.BooleanField(default=False, verbose_name='lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
