# Generated by Django 6.0.2 on 2026-02-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default="OAIB - Olympiades d'IA du Benin", max_length=200, verbose_name='nom du site')),
                ('site_description', models.TextField(blank=True, verbose_name='description du site')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='email de contact')),
                ('support_email', models.EmailField(blank=True, max_length=254, verbose_name='email support')),
                ('registration_open', models.BooleanField(default=True, verbose_name='inscriptions ouvertes')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='mode maintenance')),
                ('max_file_size_mb', models.PositiveSmallIntegerField(default=10, verbose_name='taille max fichier (Mo)')),
                ('allowed_file_types', models.CharField(default='pdf,jpg,png', max_length=200, verbose_name='types de fichiers autorises')),
                ('security_settings', models.JSONField(blank=True, default=dict, help_text='{"two_factor_required": false, "session_timeout": 30, "max_login_attempts": 5, "password_min_length": 8}', verbose_name='parametres de securite')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis a jour le')),
            ],
            options={
                'verbose_name': 'parametres plateforme',
                'verbose_name_plural': 'parametres plateforme',
            },
        ),
    ]
