# Generated by Django 6.0.2 on 2026-02-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='question')),
                ('answer', models.TextField(verbose_name='reponse')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='categorie')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], max_length=20, verbose_name='type de media')),
                ('file', models.FileField(upload_to='media_uploads/%Y/%m/', verbose_name='fichier')),
                ('size_bytes', models.PositiveIntegerField(default=0, verbose_name='taille (octets)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploade le')),
            ],
            options={
                'verbose_name': 'media',
                'verbose_name_plural': 'medias',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('excerpt', models.CharField(blank=True, max_length=500, verbose_name='extrait')),
                ('content', models.TextField(verbose_name='contenu')),
                ('image', models.ImageField(blank=True, upload_to='news/', verbose_name='image')),
                ('status', models.CharField(choices=[('published', 'Publie'), ('draft', 'Brouillon')], default='draft', max_length=20, verbose_name='statut')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='auteur')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publie le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('content', models.TextField(verbose_name='contenu')),
                ('status', models.CharField(choices=[('published', 'Publie'), ('draft', 'Brouillon')], default='draft', max_length=20, verbose_name='statut')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='derniere modification')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='logo')),
                ('website', models.URLField(blank=True, verbose_name='site web')),
                ('tier', models.CharField(choices=[('gold', 'Or'), ('silver', 'Argent'), ('bronze', 'Bronze')], default='bronze', max_length=10, verbose_name='niveau')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'partenaire',
                'verbose_name_plural': 'partenaires',
                'ordering': ['display_order'],
            },
        ),
    ]
