# Generated by Django 5.2.11 on 2026-02-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('role', models.CharField(max_length=300, verbose_name='rôle/titre')),
                ('quote', models.TextField(verbose_name='témoignage')),
                ('image', models.ImageField(blank=True, upload_to='testimonials/', verbose_name='photo')),
                ('video_url', models.URLField(blank=True, help_text='Lien vers une vidéo YouTube ou Vimeo (optionnel)', verbose_name='URL vidéo (YouTube/Vimeo)')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': 'témoignage',
                'verbose_name_plural': 'témoignages',
                'ordering': ['display_order'],
            },
        ),
    ]
