# Generated by Django 6.0.2 on 2026-02-07 18:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin'), ('O', 'Autre')], max_length=1, verbose_name='genre')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('country', models.CharField(default='Benin', max_length=100, verbose_name='pays')),
                ('school', models.CharField(blank=True, max_length=200, verbose_name='etablissement')),
                ('level', models.CharField(blank=True, choices=[('Seconde', 'Seconde'), ('Premiere', 'Premiere'), ('Terminale', 'Terminale')], max_length=20, verbose_name='niveau')),
                ('class_name', models.CharField(blank=True, max_length=50, verbose_name='classe/serie')),
                ('average_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='moyenne generale')),
                ('math_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='note maths')),
                ('science_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='note sciences')),
                ('region', models.CharField(blank=True, choices=[('Littoral', 'Littoral'), ('Oueme', 'Oueme'), ('Atlantique', 'Atlantique'), ('Borgou', 'Borgou'), ('Atacora', 'Atacora'), ('Zou', 'Zou'), ('Collines', 'Collines'), ('Mono', 'Mono'), ('Couffo', 'Couffo'), ('Plateau', 'Plateau'), ('Alibori', 'Alibori'), ('Donga', 'Donga')], max_length=20, verbose_name='region')),
                ('status', models.CharField(choices=[('incomplete', 'Incomplet'), ('pending', 'En attente'), ('approved', 'Valide'), ('rejected', 'Rejete')], default='incomplete', max_length=20, verbose_name='statut')),
                ('profile_completion', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='completion du profil (%)')),
                ('admin_comment', models.TextField(blank=True, verbose_name='commentaire admin')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='inscrit le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis a jour le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'profil candidat',
                'verbose_name_plural': 'profils candidats',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom du fichier')),
                ('doc_type', models.CharField(choices=[('bulletin', 'Bulletin scolaire'), ('certificate', 'Certificat'), ('other', 'Autre')], max_length=20, verbose_name='type de document')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='fichier')),
                ('size_bytes', models.PositiveIntegerField(default=0, verbose_name='taille (octets)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('verified', 'Verifie'), ('rejected', 'Rejete')], default='pending', max_length=20, verbose_name='statut')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploade le')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='candidates.candidateprofile', verbose_name='candidat')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TutorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='prenom')),
                ('last_name', models.CharField(max_length=100, verbose_name='nom')),
                ('relationship', models.CharField(choices=[('Pere', 'Pere'), ('Mere', 'Mere'), ('Tuteur legal', 'Tuteur legal'), ('Oncle', 'Oncle'), ('Tante', 'Tante'), ('Autre', 'Autre')], max_length=20, verbose_name='lien de parente')),
                ('phone', models.CharField(max_length=20, verbose_name='telephone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_info', to='candidates.candidateprofile', verbose_name='candidat')),
            ],
            options={
                'verbose_name': 'info tuteur',
                'verbose_name_plural': 'infos tuteurs',
            },
        ),
    ]
