# Generated by Django 6.0.2 on 2026-02-07 18:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True, verbose_name='annee')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=False, verbose_name='edition active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
            ],
            options={
                'verbose_name': 'edition',
                'verbose_name_plural': 'editions',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60, verbose_name='duree (minutes)')),
                ('questions_count', models.PositiveSmallIntegerField(default=20, verbose_name='nombre de questions')),
                ('passing_score', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='score de passage (%)')),
                ('randomize_questions', models.BooleanField(default=True, verbose_name='questions aleatoires')),
                ('show_correct_answers', models.BooleanField(default=False, verbose_name='afficher les reponses')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='debut')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='fin')),
                ('status', models.CharField(choices=[('upcoming', 'A venir'), ('active', 'En cours'), ('completed', 'Termine')], default='upcoming', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
            ],
            options={
                'verbose_name': 'examen',
                'verbose_name_plural': 'examens',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='enonce')),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='medium', max_length=10, verbose_name='difficulte')),
                ('points', models.PositiveSmallIntegerField(default=1, verbose_name='points')),
                ('time_limit_seconds', models.PositiveSmallIntegerField(default=60, verbose_name='temps limite (secondes)')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name="nombre d'utilisations")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis a jour le')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'categorie de question',
                'verbose_name_plural': 'categories de questions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='commence le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='termine le')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='temps passe (secondes)')),
                ('tab_switch_count', models.PositiveSmallIntegerField(default=0, verbose_name='changements onglet')),
                ('status', models.CharField(choices=[('not_started', 'Non commence'), ('in_progress', 'En cours'), ('completed', 'Termine'), ('evaluated', 'Evalue')], default='not_started', max_length=20, verbose_name='statut')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='score')),
                ('max_score', models.PositiveSmallIntegerField(default=0, verbose_name='score max')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='pourcentage')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='classement')),
                ('category_scores', models.JSONField(blank=True, default=list, verbose_name='scores par categorie')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='candidates.candidateprofile', verbose_name='candidat')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exams.exam', verbose_name='examen')),
            ],
            options={
                'verbose_name': "session d'examen",
                'verbose_name_plural': "sessions d'examen",
                'ordering': ['-started_at'],
                'unique_together': {('candidate', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_number', models.PositiveSmallIntegerField(verbose_name='numero de phase')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('start_date', models.DateField(verbose_name='date de debut')),
                ('end_date', models.DateField(verbose_name='date de fin')),
                ('status', models.CharField(choices=[('upcoming', 'A venir'), ('active', 'En cours'), ('completed', 'Terminee')], default='upcoming', max_length=20, verbose_name='statut')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='exams.edition', verbose_name='edition')),
            ],
            options={
                'verbose_name': 'phase',
                'verbose_name_plural': 'phases',
                'ordering': ['edition', 'phase_number'],
                'unique_together': {('edition', 'phase_number')},
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exams.phase', verbose_name='phase'),
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question')),
            ],
            options={
                'verbose_name': "question d'examen",
                'verbose_name_plural': "questions d'examen",
                'ordering': ['exam', 'order'],
                'unique_together': {('exam', 'question')},
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='exams', through='exams.ExamQuestion', to='exams.question', verbose_name='questions'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='exams.questioncategory', verbose_name='categorie'),
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='texte')),
                ('is_correct', models.BooleanField(default=False, verbose_name='reponse correcte')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'option de reponse',
                'verbose_name_plural': 'options de reponse',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='reponse correcte')),
                ('is_flagged', models.BooleanField(default=False, verbose_name='marquee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examsession', verbose_name='session')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question', verbose_name='question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.questionoption', verbose_name='option choisie')),
            ],
            options={
                'verbose_name': 'reponse examen',
                'verbose_name_plural': 'reponses examen',
                'unique_together': {('session', 'question')},
            },
        ),
    ]
