# Generated by Django 5.2.11 on 2026-02-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse email')),
                ('password_hash', models.CharField(max_length=255, verbose_name='mot de passe (hash)')),
                ('first_name', models.CharField(max_length=150, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=150, verbose_name='nom')),
                ('phone', models.CharField(max_length=20, verbose_name='téléphone')),
                ('birth_date', models.DateField(verbose_name='date de naissance')),
                ('otp_code', models.CharField(max_length=10, verbose_name='code OTP')),
                ('otp_expires_at', models.DateTimeField(verbose_name='expiration OTP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': 'inscription en attente',
                'verbose_name_plural': 'inscriptions en attente',
                'ordering': ['-created_at'],
            },
        ),
    ]
