# Generated by Django 6.0.2 on 2026-02-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video'), ('link', 'Lien'), ('article', 'Article'), ('exercise', 'Exercice')], max_length=20, verbose_name='type')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('file', models.FileField(blank=True, upload_to='resources/', verbose_name='fichier')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='categorie')),
                ('phase', models.PositiveSmallIntegerField(blank=True, help_text='Phase de la competition (1-6)', null=True, verbose_name='phase associee')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
            ],
            options={
                'verbose_name': 'ressource',
                'verbose_name_plural': 'ressources',
                'ordering': ['-created_at'],
            },
        ),
    ]
